In [1]:
a = [16, 17, 4, 3, 5, 2]
b = len(a)
c = b-2
for i in range(c):
    if a[i] < a[i+1]:
        print(a[i+1])
print(a[-1])

17
5
2


In [2]:
a = [16, 17, 4, 3, 5, 2]
leaders = []

for i in range(len(a)):
    if a[i] == max(a[i:]):
        leaders.append(a[i])

print("Leader numbers:", leaders)


Leader numbers: [17, 5, 2]


In [3]:

def zigzag(arr, n):
    flag = True
    for i in range (n - 1):
        if flag is True:
            if arr[i] > arr[i + 1]:
                arr[i], arr [i+1] = arr[i + 1], arr[i]
                
        else:
            if arr[i] < arr[i + 1]:
                arr[i], arr[i + 1] = arr[i +1], arr[i]
                
        flag = bool(1 - flag)
    print(arr)  

arr = [4, 3, 7, 8, 6, 2, 1]
n = len(arr)
zigzag(arr, n)

[3, 7, 4, 8, 2, 6, 1]


In [4]:
a = [4, 3, 7, 8, 6, 2, 1]

for i in range(len(a)-1):
    if (i % 2 == 0) == (a[i] > a[i+1]):
        a[i], a[i+1] = a[i+1], a[i]

print("Zigzag ordered array:", a)


Zigzag ordered array: [3, 7, 4, 8, 2, 6, 1]


In [5]:
arr = [4,3,7,8,6,2,1]
b = len(a)
for i in range(b-1):
    if (i % 2 == 0) == arr[i] > arr[i + 1]:
        arr[i], arr [i+1] = arr[i + 1], arr[i]
    else:
        arr[i], arr[i + 1] = arr[i +1], arr[i]
print(arr)

[3, 7, 8, 6, 2, 1, 4]


In [6]:
a = [4,3,7,8,6,2,1]
c = a
b = a.sort()
print(a)
for i in range(1,len(a)-1):
    print(c[i],c[i+1])
    i+=1
print(c[0])  


[1, 2, 3, 4, 6, 7, 8]
2 3
3 4
4 6
6 7
7 8
1


In [7]:
def find_missing_number(nums):
    n = len(nums) + 1  
    expected_sum = n * (n + 1) // 2 

    actual_sum = sum(nums)

    missing_number = expected_sum - actual_sum 
    return missing_number
numbers = [1, 2, 4, 3, 6, 7, 8]  
missing = find_missing_number(numbers)
print("The missing number is:", missing)

The missing number is: 5


In [8]:
a = [1, 2, 4, 3, 6, 7, 8]
b = a.sort()
print(a)
count = 0
n = len(a)-2
for i in range(n):
    if a[i+1]-a[i]==1:
        count+=0
        if count == 1:
            break
        else:
            print(a[i]+1)


[1, 2, 3, 4, 6, 7, 8]
2
3
4
7


In [9]:
def find_three_numbers(arr, target_sum):
    n = len(arr)
    arr.sort()
    for i in range(n - 2):
        left, right = i + 1, n - 1
        while left < right:
            current_sum = arr[i] + arr[left] + arr[right]
            if current_sum == target_sum:
                return [arr[i], arr[left], arr[right]]
            elif current_sum < target_sum:
                left += 1
            else:
                right -= 1
    return []
arr = [1, 2, 3, 4, 5]
target_sum = 9

result = find_three_numbers(arr, target_sum)
if result:
    print("Three numbers that sum to 9:", result)
else:
    print("No such triplet found.")

Three numbers that sum to 9: [1, 3, 5]


In [10]:
#sum of three numbers 
a = [1,2,3,4,5]
l = len(a)
for i in range(l):
    for j in range(i+1,l):
        for k in range(j+1,l):
            if(a[i]+a[j]+a[k]==9):
                print(a[i], a[j], a[k])          


1 3 5
2 3 4


In [11]:

#sum of three numbers
a =[1,2,3,4,5]
l = len(a)
for i in range(l-2):
    for j in range(i+1,l):
         if(a[i]+a[i+2]+a[j]==9):
                print(a[i],a[i+2],a[j])


1 3 5
2 4 3


In [12]:
#sum of three numbers
a =[12,3,4,1,6,9]
l = len(a)
for i in range(l-2):
    for j in range(i+1,l):
         for k in range(j+1,l):
            if(a[i]+a[j]+a[k]==24):
                print(a[i], a[j], a[k])          


12 3 9


In [13]:

a=[0,0,1,2,0,1,2,2,1]
l = len(a)
for i in range(l):
    if(a[i]==0):
        print(a[i],end="")
for i in range(l):
    if(a[i]==1):
        print(a[i],end="")
for i in range(l):
    if(a[i]==2):
        print(a[i],end="")

000111222

In [14]:
#print spiral matrix
import numpy as np
x = np.arange(1, 17).reshape(4, 4)
x
print(x)
for i in range(4):
    for j in range(4):
        if (i ==0 and j <3 ):
            print(x[i][j])
for i in range(4):
    for j in range(4):
        if (i<3 and j==3):
            print(x[i][j])
for i in range(4):
    for j in range(4):
        if (i==3):
            j=j-1
            print(x[i][j])
for i in range(4):
    for j in range(4):
        if((i==2 or i ==1) and (j==0)):
            print(x[i][j])
for i in range(4):
    for j in range(4):
        if(i ==1 and 0<j<3):
            print(x[i][j])
for i in range(4):
    for j in range(4):
        if(i==2 and 0<j<3):
            print(x[i][j])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
1
2
3
4
8
12
16
13
14
15
5
9
6
7
10
11


In [15]:
# MERGE SORT
a=[6,4,2,1,9,8,3,5]
i =[]
b = len(a)
c = (b//2)-1
d = b-c
for i in range(c):
    e = [c/2]
    if e==2:
        if a[1]>a[0]:
            i.append(a[1])
        else:
            i.append(a[0],a[1])  

In [16]:
def merge_sort(arr):
    if len(arr) <= 1:
        return arr

    mid = len(arr) // 2
    left_half = arr[:mid]
    right_half = arr[mid:]

    left_half = merge_sort(left_half)
    right_half = merge_sort(right_half)

    return merge(left_half, right_half)

def merge(left, right):
    result = []
    i = j = 0

    while i < len(left) and j < len(right):
        if left[i] < right[j]:
            result.append(left[i])
            i += 1
        else:
            result.append(right[j])
            j += 1

    result.extend(left[i:])
    result.extend(right[j:])
    return result

# Example usage:
my_list = [6,4,2,1,9,8,3,5]
sorted_list = merge_sort(my_list)
print("Sorted array:", sorted_list)


Sorted array: [1, 2, 3, 4, 5, 6, 8, 9]


In [17]:
def mergeSort(arr):
    if len(arr) > 1:
        mid = len(arr)//2
        sub_array1 = arr[:mid]
        sub_array2 = arr[mid:]
        mergeSort(sub_array1)
        mergeSort(sub_array2)
        i = j = k = 0
        while i < len(sub_array1) and j < len(sub_array2):
            if sub_array1[i] < sub_array2[j]:
                arr[k] = sub_array1[i]
                i += 1
            else:
                arr[k] = sub_array2[j]
                j += 1
            k += 1
        while i < len(sub_array1):
            arr[k] = sub_array1[i]
            i += 1
            k += 1
        while j < len(sub_array2):
            arr[k] = sub_array2[j]
            j += 1
            k += 1
 
arr = [6,4,2,1,9,8,3,5]
mergeSort(arr)
print(arr)


[1, 2, 3, 4, 5, 6, 8, 9]


In [18]:
def merge_sort(A, p, r):
    if p < r:
        q = (p + r) // 2
        merge_sort(A, p, q)       
        merge_sort(A, q + 1, r)   
        merge(A, p, q, r)         


def merge(A, p, q, r):
    n1 = q - p + 1
    n2 = r - q

    
    L = [0] * (n1 + 1)
    R = [0] * (n2 + 1)

    
    for i in range(n1):
        L[i] = A[p + i]
    for j in range(n2):
        R[j] = A[q + 1 + j]

   
    L[n1] = float('inf')
    R[n2] = float('inf')

    i = 0
    j = 0

    
    for k in range(p, r + 1):
        if L[i] <= R[j]:
            A[k] = L[i]
            i += 1
        else:
            A[k] = R[j]
            j += 1


arr = [6,4,2,1,9,8,3,5]
merge_sort(arr, 0, len(arr) - 1)
print("Sorted array:", arr)

Sorted array: [1, 2, 3, 4, 5, 6, 8, 9]


In [19]:
a=[1,10,11,12,11,1]
b =[]
for i in range(len(a)-1):
        if a[i]!=a[i+1]:
            b.append(a[i])
            c = set(b)
print(c)

{1, 10, 11, 12}


In [20]:
a = [1,10,11,12,11,1]
b = []
for i in range(len(a)-1):
        if a[i]==a[i+1]:
            continue
        else:
            b.append(a[i])
print(b)


[1, 10, 11, 12, 11]


In [22]:
class cll:
    def __init__(self,data,next=None):
        self.head = head
        self.next = next

node1 = listnode(1)
node2 = listnode(2)
node3 = listnode(3)
node4 = listnode(4)

node1.next = node2
node2.next = node3
node3.next = node4
node4.next = node2

while

SyntaxError: invalid syntax (306985729.py, line 16)

In [23]:
# MERGE SORT
def MSort(a):
    if len(a) > 1:
        mid = len(a)//2
        s1 = a[:mid]
        s2 = a[mid:]
        MSort(s1)
        MSort(s2)
        i = j = k = 0
        while i < len(s1) and j < len(s2):
            if s1[i] < s2[j]:
                a[k] = s1[i]
                i += 1
            else:
                a[k] = s2[j]
                j += 1
            k += 1
        while i < len(s1):
            a[k] = s1[i]
            i += 1
            k += 1
        while j < len(s2):
            a[k] = s2[j]
            j += 1
            k += 1
a = [6,4,2,1,9,8,3,0,5,-7]
MSort(a)
print("Sorted array:",a)

Sorted array: [-7, 0, 1, 2, 3, 4, 5, 6, 8, 9]


In [24]:
import numpy as np
values = [10, 11, 12, 31, 32, 33, 41, 42, 43]
x = np.array(values).reshape(3, 3)
for i in range(3):
    for j in range(3):
        if(i<3 and j==2):
            print(x[i][j],end=" ")
print("")
for i in range(3):
    for j in range(3):
        if(i<3 and j==1):
            print(x[i][j],end=" ")  
print("")
for i in range(3):
    for j in range(3):
        if(i<3 and j==0):
            print(x[i][j],end=" ")


12 33 43 
11 32 42 
10 31 41 

In [25]:
import numpy as np
values = [0,1,2,3,4,5,6,7,8]
x = np.array(values).reshape(3, 3)
print(x)
print("")
for i in range(3):
    for j in range(3):
        x[0][0],x[0][2] = x[0][2],x[0][0] 
        x[2][0],x[2][2] = x[2][2],x[2][0]
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[2 1 0]
 [3 4 5]
 [8 7 6]]


In [26]:
a=[2,5,6,1,3,4,10,9,8,7]
for i in range(1,len(a)):
    a[i]=i
print(a)


[2, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [27]:
a=[2,3,1,0,4,5,7,6,9,8]
for i in range(len(a)):
    a[i]=i
print(a)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [28]:
a=[2,3,1,0,4,5,7,6,9,8]
for i in range(len(a)):
    temp = a[i]
    i = temp
    i = a[i]
print(a)

[2, 3, 1, 0, 4, 5, 7, 6, 9, 8]


In [29]:
array = [2, 3, 1, 0, 4, 5, 7, 6, 9, 8]

for i in range(len(array)):
    min_index = i
    for j in range(i + 1, len(array)):
        if array[j] < array[min_index]:
            min_index = j

    if min_index != i:
        array[i], array[min_index] = array[min_index], array[i]
print(array)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [30]:
array = [2, 3, 1, 0, 4, 5, 7, 6, 9, 8]
new_array = [ ]
for i in range(len(array)):
    min_value = min(array)
    new_array.append(min_value)
    array.remove(min_value)
print(new_array)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [31]:
def minimize_curse(teachers, D):
    teachers.sort(key=lambda teacher: teacher[2])
    curse_level = 0  
    schedule = [0] * (D + 1)
    for teacher in teachers:
        arrival_day, required_lectures, curse_increase = teacher
        for day in range(arrival_day, min(D, arrival_day + required_lectures)):
            if schedule[day] < required_lectures:
                schedule[day] += 1
            else:
                break
        untaught_lectures = required_lectures - sum(schedule[arrival_day:arrival_day + required_lectures])
        curse_level += untaught_lectures * curse_increase
    return curse_level
teachers = [(2, 3, 5), (1, 2, 10), (3, 1, 2)]
D = 4
min_curse = minimize_curse(teachers, D)
print(min_curse)

-10


In [32]:

matrix= [6,7,8]
print(matrix)

[6, 7, 8]


In [33]:
matrix = [[1, 0, 1, 1],
          [1, 1, 1, 1],
          [1, 0, 1, 0],
          [1, 0, 0, 1]]
a = len(matrix)
for i in range(a):
    count = 0
    for j in range(a):
        if(matrix[i][j] == 1):
            count+=1
        else:
            continue
    print(count)   

3
4
2
2


In [34]:

import numpy as py
x = [7,6,5,1,2,3,8,4,9]
y = np.array(x).reshape(3, 3)
print(y)
for i in range(len(x)):
    min_index = i
    for j in range(i + 1, len(x)):
        if x[j] < x[min_index]:
            min_index = j
    if min_index != i:
        x[i], x[min_index] = x[min_index], x[i]
z = np.array(x).reshape(3, 3)
print(z)
for i in range(3):
    for j in range(3):
        if i == j:
            y[i][j] = 0
        elif((i==0 and j==2) or (i==2 and j==0)):
            y[i][j] = 0
a = np.array(y).reshape(3,3)
print(a)

[[7 6 5]
 [1 2 3]
 [8 4 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 6 0]
 [1 0 3]
 [0 4 0]]


In [35]:

a = int(input("Enter your first number: "))
b = int(input("Enter your second number: "))
i=0
c=0
while i<b:
    c+=a
    i+=1
print(c)

Enter your first number: 3
Enter your second number: 4
12


In [36]:
class Node:
    def __init__ (self,value):
        self.value = value
        self.left = None
        self.right = None
def search_bst(root,ele):
    if root is None:
        return False
    if root.value == ele:
        return True
    if ele < root.value:
        return search_bst(root.left, ele)
    else:
        return search_bst(root.right, ele)
root = Node(10)
root.left = Node(8)
root.right = Node(20)
root.left.left = Node(7)
root.left.right = Node(9)
root.right.left = Node(15)
root.right.right = Node(21)
ele = int(input("Enter the elements to search for: "))
found = search_bst(root,ele)
if found:
    print("Found".format(ele))
else:
    print("Not found". format(ele))

Enter the elements to search for: 3
Not found


In [37]:
class Node:
    def __init__ (self,value):
        self.value = value
        self.left = None
        self.right = None
def sumofleafnodes(root):
    if root is None:
        return 0
    elif root.left is None and root.right is None:
        return root.value
    return sumofleafnodes(root.left) + sumofleafnodes(root.right)
root = Node(10)
root.left = Node(8)
root.right = Node(20)
root.left.left = Node(7)
root.left.right = Node(9)
root.right.left = Node(15)
root.right.right = Node(21)
sum = sumofleafnodes(root)
print("The sum of all leaf nodes is ",format(sum))


The sum of all leaf nodes is  52


In [38]:
class Node:
    def __init__(self, key):
        self.data = key
        self.left = None
        self.right = None
def printSpiral(root):
    if root is None:
        return
    stack1 = []  
    stack2 = []  
    stack1.append(root)  # Start with the root node
    while stack1 or stack2:
        while stack1:
            node = stack1.pop()
            print(node.data, end=" ")

            if node.left:
                stack2.append(node.left)
            if node.right:
                stack2.append(node.right)
        while stack2:
            node = stack2.pop()
            print(node.data, end=" ")
            if node.right:
                stack1.append(node.right)
            if node.left:
                stack1.append(node.left)
root = Node(1)
root.left = Node(2)
root.right = Node(3)
root.left.left = Node(4)
root.left.right = Node(5)
root.right.left = Node(6)
root.right.right = Node(7)
root.left.left.left = Node(8)
root.left.left.right = Node(9)
root.left.right.left = Node(10)
root.left.right.right = Node(11)
root.right.left.left = Node(12)
root.right.left.right = Node(13)
root.right.right.left = Node(14)
root.right.right.right = Node(15)
print("Spiral Order traversal of the BST:")
printSpiral(root)


Spiral Order traversal of the BST:
1 3 2 4 5 6 7 15 14 13 12 11 10 9 8 

In [ ]:
N, D = map(int, input().split())
teachers = []
for _ in range(N):
    teachers.append(list(map(int, input().split())))


In [ ]:
# Sorting the teachers based on their arrival day
teachers.sort(key=lambda x: x[0])

curse_level = 0
lectures_scheduled = 0

for teacher in teachers:
    if D <= teacher[0]:
        break

    possible_lectures = min(D - teacher[0] + 1, teacher[1] - lectures_scheduled)
    curse_level += teacher[2] * (teacher[1] - possible_lectures - lectures_scheduled)
    lectures_scheduled += possible_lectures

print(curse_level)


In [ ]:
import heapq

def dijkstra(graph, start, end, unsafe):
    n = len(graph)
    distances = [float('inf')] * n
    distances[start] = 0
    heap = [(0, start)]

    while heap:
        (dist, current) = heapq.heappop(heap)

        if current == end:
            return distances[end]

        for neighbor, weight in graph[current]:
            if dist + weight < distances[neighbor] and not (unsafe[neighbor] <= dist + weight < unsafe[neighbor] + 5):
                distances[neighbor] = dist + weight
                heapq.heappush(heap, (distances[neighbor], neighbor))

    return distances[end]

# Input parsing
n, m = map(int, input().split())
graph = [[] for _ in range(n)]
unsafe = [0] * n

for _ in range(m):
    u, v, t = map(int, input().split())
    graph[u - 1].append((v - 1, t))
    graph[v - 1].append((u - 1, t))
    unsafe[u - 1] = t
    unsafe[v - 1] = t


In [ ]:
n, d = map(int, input().split())
teachers = []
for _ in range(n):
    di, ti, si = map(int, input().split())
    teachers.append((si, di, ti))
teachers.sort(reverse=True)
schedule = [0] * d
for si, di, ti in teachers:
    for i in range(di, d):
        if not schedule[i]:
            schedule[i] = si
            break
print(sum(schedule))

In [ ]:
N, D = list(map(int, input().split()))
teachers = []
for i in range(N):
    arrival_day, lectures, curse_level = list(map(int, input().split()))
    teachers.append([arrival_day, lectures, curse_level])
def bubble_sort(arr):
    for i in range(len(arr) - 1):
        for j in range(len(arr) - 1):
            if arr[j][2] < arr[j + 1][2]:
                arr[j], arr[j + 1] = arr[j + 1], arr[j]
    return arr
def evaluate(teachers):
    total_curse = 0
    lecture_schedule = [[-1, -1, -1], [-1, -1, -1]]
    for day in range(1, D + 1):
        for teacher in teachers:
            if teacher[0] == day:
                lecture_schedule.append(teacher)
        bubble_sort(lecture_schedule)
        lecture_schedule[0][1] -= 1
        lecture_schedule += [[1, 0, 0] for _ in range(len(lecture_schedule))]
        lecture_schedule = [teacher for teacher in lecture_schedule if teacher[1] > 0]
    for teacher in lecture_schedule:
        if teacher[1] > 0:
            total_curse += teacher[2] * teacher[1]
    print(total_curse)
evaluate(teachers)